prepare for homebrew

diff --git a/toggle-wifi b/toggle-wifi
--- a/toggle-wifi
+++ b/toggle-wifi
@@ -1,33 +1,15 @@
 #!/bin/bash
 
-# Search for python3 installation, prefer homebrew
+# Search for python3 installation
 if ! command -v brew &> /dev/null ; then
-    echo "WARNING: Homebrew not on PATH!"
-    if ! test -f "/opt/homebrew/bin/brew"; then
-        if ! test -f "/usr/local/bin/brew"; then
-            echo "WARNING: Homebrew not found! Trying to use systems python3!"
-            if ! command -v python3 &> /dev/null ; then
-                echo "ERROR: python3 not found"
-                exit 1
-            else
-                PYTHON3=$(which python3)
-            fi
-        else
-            PYTHON3="/usr/local/bin/python3"
-        fi
-    else
-        PYTHON3="/opt/homebrew/bin/python3"
-    fi
-else
-    if ! brew ls --versions python > /dev/null; then
-        echo "WARNING: python3 not installed via homebrew! Trying to use systems python3!"
-        if ! command -v python3 &> /dev/null ; then
-            echo "ERROR: python3 not found"
-            exit 1
-        fi
-    else
-        PYTHON3=$(which python3)
-    fi
+    echo "ERROR: Homebrew not on PATH!"
+    exit 1
+fi
+if ! brew ls --versions python > /dev/null; then
+    echo "ERROR: python3 not found"
+    exit 1
 fi
 
-$PYTHON3 "$0.py"
+VERSION=$(brew ls --versions toggle-wifi | awk '{ print $2 }')
+HOMEBREW_PREFIX=$(brew --prefix)
+python3 $HOMEBREW_PREFIX/Cellar/toggle-wifi/$VERSION/toggle-wifi.py
